name: Build
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    build:
        strategy:
            matrix:
                include:
                    - platform: web
                      os: ubuntu-latest
                    - platform: macos
                      os: macos-latest
                    - platform: linux
                      os: ubuntu-latest
        name: build-${{ matrix.platform }}
        runs-on: ${{ matrix.os }}
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Build
              run: flutter build -v ${{ matrix.platform }}