name: Build for web
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Build
              run: flutter build -v web