name: Build for web
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - uses: actions/checkout@v4
            - run: flutter build -v web