name: Release
on:
    workflow_dispatch:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    trigger-test:
        uses: ./.github/workflows/test.yml
    build-release:
        strategy:
            matrix:
                include:
                    - platform: web
                      os: ubuntu-latest
                      environment: onrender
                    - platform: macos
                      os: macos-latest
        name: build-${{ matrix.platform }}-release
        concurrency: build-${{ github.ref }}-${{ matrix.platform }}
        runs-on: ${{ matrix.os }}
        needs: trigger-test
        environment: ${{ matrix.environment }}
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Set version environment variable
              run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV      
            - name: Build release
              run: flutter build -v ${{ matrix.platform }} --release --build-name=${{ env.VERSION }} --build-number=${{ github.sha }} --dart-define=VERSION=${{ env.VERSION }} --dart-define=COMMIT_SHA=${{ github.sha }} --dart-define=REPO_URL=${{ github.server_url }}/${{ github.repository }}
            - name: '[web] Commit build to onrender branch'
              if: ${{ matrix.platform == 'web' }}
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: build/web
                branch: onrender
            - name: '[web] Print Render dashboard link'
              if: ${{ matrix.platform == 'web' }}
              run: echo "Follow the deploy pipeline at https://dashboard.render.com/static/srv-ckkutdqv7m0s73cts10g/events"
            - name: '[macos] Compress build'
              if: ${{ matrix.platform == 'macos' }}
              run: |
                cd build/macos/Build/Products/Release
                tar -czf sourdoc.app.tgz sourdoc.app
            - name: '[macos] Upload app artifact'
              if: ${{ matrix.platform == 'macos' }}
              uses: actions/upload-artifact@v3
              with:
                name: sourdoc.app
                path: build/macos/Build/Products/Release/sourdoc.app.tgz
    create-github-release:
      concurrency: release-${{ github.ref }}
      runs-on: ubuntu-latest
      needs: build-release
      steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 1
          - name: Set version environment variable
            run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV   
          - name: Download artifacts
            uses: actions/download-artifact@v3
            with:
              name: sourdoc.app
              path: .
          - name: Create release
            uses: softprops/action-gh-release@v1
            with:
              tag_name: v${{ env.VERSION }}
              files: |
                sourdoc.app.tgz