name: Tag version
on:
    push:
        branches:
            - main
        paths:
            - VERSION
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-tags: true
            - run: git push origin :refs/tags/v${cat VERSION}
            - run: git tag -fa v${cat VERSION}
            - run: git push origin --tags