name: Tag version
on:
    push:
        branches:
            - main
        paths:
            - VERSION
permissions:
    contents: write
jobs:
    tag-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Tag
              run: git tag v$(cat VERSION)
            - name: Push
              run: git push origin --tags