name: Test
on:
    workflow_call:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Flutter test
              run: flutter test --coverage -r github
    integration-test:
        runs-on: macos-latest
        steps:
            # - name: Install dependencies
            #   run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
            # - name: Setup java
            #   uses: actions/setup-java@v3
            #   with:
            #     java-version: 17
            #     distribution: temurin
            # - name: Setup android sdk
            #   uses: android-actions/setup-android@v3
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 3.13.7
                channel: stable
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            # - name: Gradle cache
            #   uses: gradle/gradle-build-action@v2
            # - name: AVD cache
            #   uses: actions/cache@v3
            #   id: avd-cache
            #   with:
            #     path: |
            #       ~/.android/avd/*
            #       ~/.android/adb*
            #     key: avd-34
            # - name: Create AVD and generate snapshot for caching
            #   if: steps.avd-cache.outputs.cache-hit != 'true'
            #   uses: reactivecircus/android-emulator-runner@v2
            #   with:
            #     api-level: 34
            #     force-avd-creation: false
            #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            #     disable-animations: false
            #     script: echo "Generated AVD snapshot for caching."        
            # - name: Flutter integration test
            #   uses: reactivecircus/android-emulator-runner@v2
            #   with:
            #     target: playstore
            #     api-level: 34
            #     arch: x86_64
            #     profile: Nexus 6
            #     force-avd-creation: false
            #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            #     disable-animations: true      
            #     script: flutter test integration_test/home_page.test.dart
            - name: Flutter integration test
              run: flutter test -v -d macos integration_test/home_page.test.dart
