name: Test
on:
    workflow_call:
    workflow_dispatch:
    push:
        branches-ignore:
            - main
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Flutter test
              run: flutter test --coverage -r github
    integration-test:
        runs-on: macos-13
        steps:
            - name: Prepare flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: ${{ vars.FLUTTER_VERSION }}
                channel: ${{ vars.FLUTTER_CHANNEL }}
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Flutter integration test
              run: flutter test -v -d macos integration_test/main.dart
