name: Web deploy monitor
on:
    workflow_dispatch:
    release: 
        types:
            - created
            - edited
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - name: Check deployment status
              run: |
                COMMIT=$(git rev-parse HEAD)
                bash cli/web_deploy_monitor.sh